baseURL: http://example.org/
languageCode: fr
title: Florian F.

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: "" # <your google analytics id>

# Enable Disqus forum
# optional
disqusShortname: "" # see https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Github Repo URL. This is used to add "Improve This Page" button
  gitRepo: https://github.com/Flooow54/MyHugoPortfolio
  mainSections: ["posts"] # the content of these sections will be displayed in "Recent Posts"


